# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 566fa22dca38d6407239733705f6b8033fb37e959b6cc602cacdad11bdd3dc54d8c4c6af60e198163db42c613d57ce0770d9a8c449aba3d9ec6bec48c81d8a17

test:
  secret_key_base: 3f4f6379de2d9b7dc136a48cc9e256a3fca70e4c09f059a19983ba6a606569584fe444f272b8cace4203e447cfe8ace482a702166c660e8fe61f4c1c03974dab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
